[project]
name = "dls-2024-1"
version = "0.1.0"
requires-python = ">= 3.11"
description = "Add a short description here"
authors = [{ name = "relicks", email = "axndr.litvinov@gmail.com" }]
readme = "README.md"
dependencies = []

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["nvidia", "conda-forge", "pytorch"]
platforms = ["linux-64", "win-64"]

[tool.pixi.pypi-dependencies]
dls_2024_1 = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.activation.env]
CC = "clang"

[tool.pixi.dependencies]
# ? numeric
numpy = { version = "*", channel = "conda-forge" }
scipy = { version = "*", channel = "conda-forge" }
pandas = { version = "*", channel = "conda-forge" }
scikit-learn = { version = "*", channel = "conda-forge" }
jaxtyping = { version = "*", channel = "conda-forge" }

# ? plots
matplotlib = { version = "*", channel = "conda-forge" }
seaborn = { version = "*", channel = "conda-forge" }

# ? torch
pytorch = { version = ">=2.1.1", channel = "pytorch" }
pytorch-cuda = { version = "12.1", channel = "pytorch" }
torchvision = { version = "*", channel = "pytorch" }
torchinfo = { version = "*", channel = "conda-forge" }

# ? jupyter
ipykernel = { version = "*", channel = "conda-forge" }
ipywidgets = { version = "*", channel = "conda-forge" }

# ? 🤗
transformers = { version = "*", channel = "conda-forge" }
datasets = { version = "*", channel = "conda-forge" }
huggingface_hub = { version = "*", channel = "conda-forge" }

# ? misc
tqdm = { version = "*", channel = "conda-forge" }
rich = { version = "*", channel = "conda-forge" }
httpx = { version = "*", channel = "conda-forge" }
beartype = { version = "*", channel = "conda-forge" }
typing_extensions = { version = "*", channel = "conda-forge" }


[tool.ruff]
line-length = 100
target-version = "py311"
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]

[tool.ruff.lint]
# isort = { known-first-party = ["libs"] }
per-file-ignores = { "*.ipynb" = [
    "F401",
    "E402",
    "PLE1142",
    "PLR2004",
], "*.pyi" = [
    "F401",
] }
select = [
    # "D",   # pydocstyle
    # "ANN", # flake8-annotations
    "TCH", # flake8-type-checking
    "FBT", # flake8-boolean-trap

    "E",    # pycodestyle
    "F",    # pyflakes
    "UP",   # pyupgrade
    "I",    # isort
    "PL",   # pylint
    "RUF",  # ruff-specific
    "N",    # pep8-naming
    "C4",   # flake8-comprehensions
    "B",    # flake8-bugbear
    "PTH",  # flake8-use-pathlib
    "TRY",  # tryceratops
    "PERF", # Perflint 
    "FURB", # refurb 
    "PT",   # flake8-pytest-style
]
ignore = [
    "PLR0913", #too-many-arguments
    "RUF001",  # ambiguous cyrillic letters
    "RUF002",  # ambiguous cyrillic letters
    "RUF003",  # ambiguous-unicode-character-comment
    "ANN101",  # missing-type-self #? deprecated
    "D202",    # no-blank-line-after-function
    "N803",    # invalid-argument-name
    "N806",    # non-lowercase-variable-in-function
    "N812",    # lowercase-imported-as-non-lowercase
    "F722",
]

[tool.pyright]
pythonVersion = "3.11"
venvPath = "./.pixi/envs"
reportPrivateImportUsage = false
reportMissingImports = true
reportMissingTypeStubs = false

#? cSpell Configuration:
# cspell: words pixi einops jaxtyping ipywidgets pygame httpx pydantic openpyxl
# cspell: words torchrl networkx mlops tryceratops FURB
